### ISSUE TITLE
Unable to download sample model

### ISSUE THREAD

**Issue by avasyub** [cpgeier/DeepGTAV_Tools#5]
Hi, could you rehost sample_model.h5 on Google drive. I'm unable to download it from GitHub.

**Comment by Lakshmibharadwaj** [comment]
Hi,
I have the same problem cant open sample_model.h5, I have this error

Traceback (most recent call last):
  File "C:\Grand Theft Auto V\drive_categorical.py", line 9, in <module>
    model = load_model('sample_model.h5') # Load trained model
  File "C:\Python35.4\lib\site-packages\keras\models.py", line 237, in load_model
    with h5py.File(filepath, mode='r') as f:
  File "C:\Python35.4\lib\site-packages\h5py\_hl\files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\Python35.4\lib\site-packages\h5py\_hl\files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

**Comment by lyzMaster** [comment]
same problem.

**Comment by cpgeier** [comment]
Removed file and added model hosted on Google Drive, check readme for sample model link
